services:
  web:
    build: .
    container_name: sistema_web
    ports: 
      - "80:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    networks:
      - startup_network
    restart: unless-stopped


  db:
    image: mysql:8.0
    container_name: sistema_mysql
    environment:
      DB_HOST: db
      DB_NAME: aval_acao
      DB_USER: user
      DB_PASS: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql/docker-entrypoint.initdb.d/init.sql
    networks:
      - startup_network
    restart: unless-stopped
  

volumes:
  mysql_data:


networks:
  startup_network:
    driver:
      bridge