services:
  web:
    build: ./public
    container_name: sistema_web
    ports: 
      - "80:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    networks:
      - startup_network
    restart: always
    environment:
       - DB_HOST=db
       - DB_NAME=aval_acao
       - DB_USER=user
       - DB_PASS=pass


  db:
    image: mysql:8.0
    container_name: sistema_mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha_do_root
      MYSQL_DATABASE: aval_acao
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - startup_network
    restart: always
  


networks:
  startup_network:
    driver:
      bridge