services:
  web:
    build: .
    container_name: sistema_web
    ports: 
      - "80:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    networks:
      - startup_network
    restart: unless-stopped


  db:
    image: mysql:8.0
    container_name: sistema_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql/docker-entrypoint.initdb.d/init.sql
    networks:
      - startup_network
    restart: unless-stopped



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistema_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
      PMA_ROOT_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - startup_network
    restart: unless-stopped
  

volumes:
  mysql_data:


networks:
  startup_network:
    driver:
      bridge